# Generated by Django 4.2.14 on 2024-08-13 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TechEventsHub', '0002_contactinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactinfo',
            name='user',
        ),
    ]
